### ISSUE TITLE
cannot import name 'Dataset_Pred' from 'data_provider.data_loader'

### ISSUE THREAD

**Issue by pikeduo** [Tims2D/Times2D#2]
It looks like the Dataset_Pred class is missing from data_provider/data_loader.py.
Also, requirements.txt is missing a packages for patool==4.0.1

**Comment by Tims2D** [comment]
Thanks for letting me know. I have fixed that!

**Comment by LiuYang826** [comment]
Hello, could you share the code of "Times2D" that you have modified? Thank you

**Comment by Tims2D** [comment]
Hello, I just updated the repository. Please let me know if you have any issues running it. Thanks!

**Comment by LiuYang826** [comment]
Problem Persists！
bash ./scripts/Times2D/longTerm/etth1.sh 
Traceback (most recent call last):
  File "/home2/liuyang/Times2D-main/run.py", line 6, in <module>
    from exp.exp_long_term_forecasting import Exp_long_term_forecasting
  File "/home2/liuyang/Times2D-main/exp/exp_long_term_forecasting.py", line 4, in <module>
    from data_provider.data_factory import data_provider
  File "/home2/liuyang/Times2D-main/data_provider/data_factory.py", line 1, in <module>
    from data_provider.data_loader import Dataset_ETT_hour, Dataset_ETT_minute, Dataset_Custom, Dataset_Pred, Dataset_M4
  File "/home2/liuyang/Times2D-main/data_provider/data_loader.py", line 6, in <module>
    from data_provider.m4 import M4Dataset, M4Meta
ModuleNotFoundError: No module named 'data_provider.m4'
T

**Comment by LiuYang826** [comment]
Please solve the following, thank you

**Comment by LiuYang826** [comment]
Hello, I encountered an error when running your "Times2D" source code: "ModuleNotFoundError: No module named 'data_provider.m4'". Could you please help me solve it? Yesterday, I saw that although your code base was updated, the problem still exists. thank you！






---- Replied Message ----
| From | Reza ***@***.***> |
| Date | 11/06/2025 15:04 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Tims2D/Times2D] cannot import name 'Dataset_Pred' from 'data_provider.data_loader' (Issue #2) |
Tims2D left a comment (Tims2D/Times2D#2)

Hello, I just updated the repository. Please let me know if you have any issues running it. Thanks!

**Comment by Tims2D** [comment]
Hello,
Thanks for letting me know. I just fixed that. Please feel free to reach
out if you have any questions!
Best,
Reza

**Comment by LiuYang826** [comment]
Hello, I have already run your latest revised code and a new error occurred:
sh ./scripts/Times2D/longTerm/etth2.sh
Traceback (most recent call last):
  File "/home2/liuyang/Times2D-main/run.py", line 6, in <module>
    from exp.exp_long_term_forecasting import Exp_long_term_forecasting
  File "/home2/liuyang/Times2D-main/exp/exp_long_term_forecasting.py", line 5, in <module>
    from exp.exp_basic import Exp_Basic
  File "/home2/liuyang/Times2D-main/exp/exp_basic.py", line 4, in <module>
    from models import Times2D,TimesNet, PatchTST, Informer, Autoformer, Transformer, DLinear, Linear, NLinear
  File "/home2/liuyang/Times2D-main/models/Autoformer.py", line 4, in <module>
    from layers.Embed import DataEmbedding, DataEmbedding_wo_pos,DataEmbedding_wo_pos_temp,DataEmbedding_wo_temp
ImportError: cannot import name 'DataEmbedding_wo_pos_temp' from 'layers.Embed' (/home2/Times2D-main/layers/Embed.py)









At 2025-11-08 14:13:40, "Reza Nematirad" ***@***.***> wrote:

Tims2D left a comment (Tims2D/Times2D#2)
Hello,
Thanks for letting me know. I just fixed that. Please feel free to reach
out if you have any questions!
Best,
Reza

**Comment by Tims2D** [comment]
Hi,
Thank you so much for letting me know. I just fixed the issue related to
the embedding layers. Please let me know if you have any
> issues running it. Thanks!

**Comment by LiuYang826** [comment]
Hello, I would like to ask if if my seq_len=96, should I adjust parameters such as 'patch_len' and 'kernel_list' in the script file, because I found that the code will cause errors after adjusting the length of the input sequence; can you give At the same time, could you please provide the scripts for processing the traffic and electricity datasets?



At 2025-11-09 15:19:42, "Reza Nematirad" ***@***.***> wrote:

Tims2D left a comment (Tims2D/Times2D#2)
Hi,
Thank you so much for letting me know. I just fixed the issue related to
the embedding layers. Please let me know if you have any
> issues running it. Thanks!

**Comment by LiuYang826** [comment]
The new problem is that after the train phase ends, it does not directly end to the next prediction length without the test phase







At 2025-11-09 15:19:42, "Reza Nematirad" ***@***.***> wrote:

Tims2D left a comment (Tims2D/Times2D#2)
Hi,
Thank you so much for letting me know. I just fixed the issue related to
the embedding layers. Please let me know if you have any
> issues running it. Thanks!

**Comment by Tims2D** [comment]
Hello.
  I really appreciate your comments on my work. I’ve updated all the codes
with the new dataset as well.
I checked them locally, and they’re running correctly. Please let me know
if you face any issues running them again. Thanks!

**Comment by LiuYang826** [comment]
Hey! I ran the Times2D_traffic.sh script and got a "no such file arguments.py" error—turns out the script uses `python -u arguments.py` but the project's entry point is actually `run.py`. Just replacing arguments.py with run.py fixes it!
Can I add scripts for ECL datasets if convenient? Thank you!



At 2025-11-11 19:34:02, "Reza Nematirad" ***@***.***> wrote:

Tims2D left a comment (Tims2D/Times2D#2)
Hello.
I really appreciate your comments on my work. I’ve updated all the codes
with the new dataset as well.
I checked them locally, and they’re running correctly. Please let me know
if you face any issues running them again. Thanks!

**Comment by LiuYang826** [comment]
I saw 'seq_len=720' in your ETT dataset. If I set it to 96, do you have to adjust the hyperparameters (kernel_list, period, patch_len, stride) in your ETT dataset? Otherwise, dimension errors will occur?





At 2025-11-11 19:34:02, "Reza Nematirad" ***@***.***> wrote:

Tims2D left a comment (Tims2D/Times2D#2)
Hello.
I really appreciate your comments on my work. I’ve updated all the codes
with the new dataset as well.
I checked them locally, and they’re running correctly. Please let me know
if you face any issues running them again. Thanks!

**Comment by Tims2D** [comment]
Hi,
If you are looking for an optimal performance, you should adjust the other
hyperparameters. But they should make sense. For example, for
input sequence length 96, it does not make sense to use a period length
greater than 96.
